VyacheslavIurevich/recompilation_postprocessor

src/main.py
Just a simple program to perform further CI.
=> init: addition of simple program

.gitignore
=> Addition of newline to the end of .gitignore

LICENSE
Our team member must be mention in our license.
=> Addition of Vasilii to LICENSE

README.md
Now our team is mentioned in README file.
=> Addition of developers team to README.md

CONTRIBUTING.md, README.md
This info is required to be mentioned in our main branch.
=> CONTRIBUTING.md actualization

.gitignore
=> Addition of project resources to .gitignore

src/function_in_runtime.py
This function checks if input function is runtime function.
=> Function runtime checker

src/function_is_plt.py
This module is to check if function is PLT trampoline.
=> Function PLT checker

.gitignore
=> Addition of .vscode/ and .idea/ to .gitignore

src/main.py, src/tools.py
This function replaces Ghidra types to types from inttypes.h and C standart types.
=> Addition of replace_types function to tools.py

src/main.py, src/tools.py
Analyzer of the data types present in the lfeat: addition of ibraries.
=> data types analyzer

src/main.py
Made a small typo, here I fix it,
=> main.py typo fix

src/main.py, src/tools.py
Now CONCATXY function automatically dump to code file.
=> Implementation of concat dumping to code file

src/main.py, src/tools.py
Now signatures are printed to C code file.
=> Signatures printing

.github/mergeable.yml
It will check PR descriptions.
=> Addition of mergeable.yml

README.md
=> feat: README.md patch

README.md
Badge confirms that our code passes Pylint CI check.
=> Addition of pylint badge

src/main.py, src/tools.py
It removes manipulations with FS register.
=> Addition of stack protection removal

src/main.py
This folder is created by Ghidra and must be removed after finishing work for cleanup.
=> Addition of project folder removal

src/main.py, src/tools.py
Types like undefinedX which are not defined by Ghidra are replaced now.
=> Addition of new types to TYPES_TO_REPLACE

src/function_code_handling.py, src/main.py, src/tools.py
-refactored single function callers removal
-refactored pattern search in code
=> Function code handling refactoring

src/function_code_handling.py
=> Update of pattern handling

src/function_code_handling.py, src/main.py, src/tools.py
Implemented a function replacing calls to variables of the form ._x_y_ with casts.
=> implementation of replacement of variable access of the form ._x_y_

src/function_code_handling.py, src/function_handling.py, src/main.py, src/tools.py
Added changing of patterns like  *(undefined (*) [16])(puVar1 + 1) = (undefined  [16])0x0; to memsets.
=> Expression cast to memset

src/tools.py
=> Fix: pylinter

src/function_code_handling.py, src/tools.py
Addition of ZEXT and SUB handling, CONCAT handling update.
=> Internal decompiled functions handling

src/main.py
Now input and output files' paths are stored in command line args written by user.
=> Addition of command line arguments handling

README.md, src/scripts/dump.py, src/scripts/main.py
Better README for our project.
=> README.md actualization, tools.py renaming

README.md
Since we use shellcheck, we need to mention it at README.md.
=> Addition of shellcheck to README.md

README.md
They are have to be written because we have executables in our repo.
=> Addition of binary files licenses to README.md

.github/workflows/lint.yml
Now it will be run in lint action.
=> Addition of shellcheсk to CI

.gitignore, README.md, ci/pylint.sh, ci/shellcheck.sh, ci/test.sh, requirements.txt, src/scripts/dump.py, src/tests/user_tests.py
Add requirements
Fixing scripts
Adding configuration instructions to the readme
=> Add requirements

src/scripts/global_variables_handling.py, src/tests/user_tests.py
=> fix: fix global data types dumping

.github/workflows/test.yml
For some reason it doesn't run tests, fixing...
=> CI Hotfix #2

.github/workflows/test.yml
Now it fails in "development" but passed on the PR. Maybe we should install requirements.
=> CI Hotfix #3
